services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - 5672:5672    # Porta AMQP
      - 15672:15672  # Porta do painel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
