version: '3.8'

services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - 5672:5672    # Porta AMQP
      - 15672:15672  # Porta do painel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ENABLED_PLUGINS_FILE: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
volumes:
  rabbitmq_data:
