services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta AMQP
      - "15672:15672"   # Porta da UI (management)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
